#see for java tunning https://docs.oracle.com/cd/E15523_01/web.1111/e13814/jvm_tuning.htm#PERFM161
version: '3.8'
services:

 ##########################################################################     
 #database service
 ##########################################################################       
  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwerty
        POSTGRES_DB: postgres  

 ##########################################################################     
 #product service
 ##########################################################################  
  calculator_provider:
    container_name: calculator-provider
    image: calculator/microservice-docker-calculator-provider:0.0.1-SNAPSHOT
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
    ports:
      - 8081:8081 
      
 ##########################################################################     
 #customer service
 ##########################################################################        
  calculator_service:
    #container_name: calculator-service
    image: calculator/microservice-docker-calculator-service:0.0.1-SNAPSHOT   
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
    deploy:
     mode: replicated
     replicas: 2
    ports:
      - "8080:8080"
      - "8082:8080"                
    depends_on:
      - postgres_db
      - calculator_provider